# -- Gitlab should be installed in it's own namespace, so when it becomes a multi-container group, it'll be isolated
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-cm
  namespace: gitlab
  labels:
    app: gitlab
data:
  # Timezone
  TZ: "Europe/Berlin"
  GITLAB_TIMEZONE: "Berlin"
  # GitLab
  GITLAB_ROOT_EMAIL: "gitlab@antimatter-studios.com"
  GITLAB_HOST: "gitlab.antimatter-studios.com"
  GITLAB_PORT: "80"
  GITLAB_SSH_HOST: "ssh.gitlab.antimatter-studios.com"
  GITLAB_SSH_PORT: "22"
  GITLAB_HTTPS: "true"
  GITLAB_NOTIFY_ON_BROKEN_BUILDS: "true"
  GITLAB_NOTIFY_PUSHER: "false"
  GITLAB_PIPELINE_SCHEDULE_WORKER_CRON: "*/5 * * * *"
  # Gitlab Registry
  GITLAB_REGISTRY_ENABLED: "true"
  GITLAB_REGISTRY_HOST: "registry.gitlab.antimatter-studios.com"
  GITLAB_REGISTRY_PORT: "443"
  GITLAB_REGISTRY_API_URL: "https://registry.gitlab.antimatter-studios.com"
  GITLAB_REGISTRY_KEY_PATH: "/certs/registry.key"
  #SSL_REGISTRY_KEY_PATH: "/certs/registry.key"
  #SSL_REGISTRY_CERT_PATH: "/certs/registry.crt"
  # GitLab Backup
  GITLAB_BACKUP_SCHEDULE: "daily"
  GITLAB_BACKUP_TIME: "04:30"
  # GitLab DB
  DB_ADAPTER: "postgresql"
  DB_HOST: "localhost"
  DB_PORT: "5432"
  # GitLab Redis
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  # Nginx settings
  NGINX_MAX_UPLOAD_SIZE: "100m"
  # GitLab SMTP settings
  GITLAB_EMAIL: "gitlab@antimatter-studios.com"
  GITLAB_EMAIL_DISPLAY_NAME: "GitLab Administrator"
  GITLAB_EMAIL_REPLY_TO: "gitlab@antimatter-studios.com"
  SMTP_ENABLED: "true"
  SMTP_DOMAIN: "antimatter-studios.com"
  SMTP_HOST: "antimatter-studios.com"
  SMTP_PORT: "995"
  SMTP_USER: "gitlab@antimatter-studios.com"
  SMTP_STARTTLS: "true"
  SMTP_AUTHENTICATION: "login"
  # Your other config vars below
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
  namespace: gitlab
  labels:
    app: gitlab
data:
  DB_USER: "gitlab"
  DB_NAME: "gitlab"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-cm
  namespace: gitlab
  labels:
    app: gitlab
data:
  REGISTRY_LOG_LEVEL: "info"
  REGISTRY_STORAGE_DELETE_ENABLED: "true"
  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/registry"
  REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: "redis"
  REGISTRY_REDIS_ADDR: "redis:6379"
  REGISTRY_AUTH_TOKEN_REALM: "https://gitlab.antimatter-studios.com/jwt/auth"
  REGISTRY_AUTH_TOKEN_SERVICE: "container_registry"
  REGISTRY_AUTH_TOKEN_ISSUER: "gitlab-issuer"
  REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: "/certs/registry.crt"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-cert-data
  namespace: gitlab
  labels:
    app: gitlab
data:
  CERT_CREATE_COUNTRY: "DE"
  CERT_CREATE_STATE: "BERLIN"
  CERT_CREATE_CITY: "Berlin"
  CERT_CREATE_ORGANISATION: "Antimatter Studios"
  CERT_CREATE_ORGANISATIONAL_UNIT: "DevOps"
  CERT_CREATE_FQDN: "registry.gitlab.antimatter-studios.com"
  CERT_CREATE_EMAIL: "gitlab@antimatter-studios.com"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-ci-runner-cm
  namespace: gitlab
  labels:
    app: gitlab-ci-runner
data:
  REGISTER_NON_INTERACTIVE: "true"
  REGISTER_LOCKED: "false"
  CI_SERVER_URL: "https://gitlab.antimatter-studios.com/ci"
  METRICS_SERVER: "0.0.0.0:9100"
  RUNNER_REQUEST_CONCURRENCY: "4"
  RUNNER_EXECUTOR: "kubernetes"
  KUBERNETES_NAMESPACE: "gitlab"
  KUBERNETES_PRIVILEGED: "true"
  KUBERNETES_CPU_LIMIT: "1"
  KUBERNETES_MEMORY_LIMIT: "1Gi"
  KUBERNETES_SERVICE_CPU_LIMIT: "1"
  KUBERNETES_SERVICE_MEMORY_LIMIT: "1Gi"
  KUBERNETES_HELPER_CPU_LIMIT: "500m"
  KUBERNETES_HELPER_MEMORY_LIMIT: "100Mi"
  KUBERNETES_PULL_POLICY: "if-not-present"
  KUBERNETES_TERMINATIONGRACEPERIODSECONDS: "10"
  KUBERNETES_POLL_INTERVAL: "5"
  KUBERNETES_POLL_TIMEOUT: "360"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-ci-runner-scripts
  namespace: gitlab
  labels:
    app: gitlab-ci-runner
data:
  run.sh: |
    #!/bin/bash
    unregister() {
        kill %1
        echo "Unregistering runner ${RUNNER_NAME} ..."
        /usr/bin/gitlab-ci-multi-runner unregister -t "$(/usr/bin/gitlab-ci-multi-runner list 2>&1 | tail -n1 | awk '{print $4}' | cut -d'=' -f2)" -n ${RUNNER_NAME}
        exit $?
    }
    trap 'unregister' EXIT HUP INT QUIT PIPE TERM
    echo "Registering runner ${RUNNER_NAME} ..."
    /usr/bin/gitlab-ci-multi-runner register -r ${GITLAB_CI_TOKEN}
    sed -i 's/^concurrent.*/concurrent = '"${RUNNER_REQUEST_CONCURRENCY}"'/' /home/gitlab-runner/.gitlab-runner/config.toml
    echo "Starting runner ${RUNNER_NAME} ..."
    /usr/bin/gitlab-ci-multi-runner run -n ${RUNNER_NAME} &
    wait