#!/usr/bin/env bash

# init the master node
kubeadm init --pod-network-cidr=10.244.0.0/16

# install your credentials to access the cluster
mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config

# install a networking layer
../upgrade/5-master-weave-net
