#!/usr/bin/env bash

echo "Enter version number to upgrade to:"
echo "** Please remember you cannot skip versions, if you are on version 1.16, you must enter 1.17 **"
read requested

[ -z "$requested" ] && echo "This is not a valid version number, exiting..." && exit 1
echo "Version requested: $requested"

version=$(apt-cache madison kubeadm | grep "$requested" | awk '{if(NR==1)print $3}')

[ -z "$version" ] && echo "Cannot find requested version '$requested', exiting..." && exit 1

apt-mark unhold kubeadm
apt-get update
apt-get install -y --allow-downgrades kubeadm=$version
apt-mark hold kubeadm

kubeadm version

