#!/usr/bin/env bash

[ -z "$1" ] && echo "This is not a valid version number, exiting..." && exit 1
echo "Version requested: $1"

version=$(apt-cache madison kubeadm | grep "$1" | awk '{if(NR==1)print $3}')

[ -z "$version" ] && echo "Cannot find requested version '$1', exiting..." && exit 1

apt-mark unhold kubeadm
apt-get update
apt-get install -y --allow-downgrades kubeadm=$version
apt-mark hold kubeadm

kubeadm version

