#!/usr/bin/env bash

echo "Enter version number to upgrade to, please remember you cannot skip versions, if you are on version 1.16, you must enter 1.17"
echo "Version requested: $1"
read requested

[ -z "$requested" ] && echo "This is not a valid version number, exiting..." && exit 1

version=$(apt-get madison kubelet | grep "$requested" | awk '{if(NR==1)print $3}')

apt-mark unhold kubelet kubectl
apt-get update
apt-get install -y kubelet=$version kubectl=$version
apt-mark hold kubelet kubectl