#!/usr/bin/env bash

kubectl get nodes || ( echo "This system does not have admin access" && exit 1 )

kubeadm upgrade plan

echo "Run the command given from the output, we can't do it automatically for you"