#!/usr/bin/env bash

[ -z "$1" ] && echo "This is not a valid version number, exiting..." && exit 1
echo "Version requested: $1"

version=$(apt-cache madison kubelet | grep "$1" | awk '{if(NR==1)print $3}')

apt-mark unhold kubelet kubectl
apt-get update
apt-get install -y kubelet=$version kubectl=$version
apt-mark hold kubelet kubectl