#!/usr/bin/env bash

kubectl get nodes 2>/dev/null || ( echo "This system does not have admin access" && exit 1 )

[ -z "$1" ] && echo "This is not a valid name, choose one from list above, exiting..." && exit 1
echo "Node requested: $1"

kubectl uncordon $1