FROM nginx:latest

RUN addgroup --gid 3000 --system app
RUN adduser --uid 3000 --system --disabled-login --disabled-password --gid 3000 app
RUN adduser nginx app

ADD ./docker/nginx.conf /etc/nginx/conf.d/default.conf
ADD ./www /www