#!/usr/bin/env bash

echo "Enter version number to upgrade to, please remember you cannot skip versions, if you are on version 1.16, you must enter 1.17"
echo "Version requested: $1"
read requested

[ -z "$requested" ] && echo "This is not a valid version number, exiting..." && exit 1

version=$(apt-get madison kubeadm | grep $requested | awk '{if(NR==1)print $3}')

[ -z "$version" ] && echo "Cannot find requested version '$requested', exiting..." && exit 1

apt-mark unhold kubeadm
apt-get update
apt-get install -y kubeadm=$version
apt-mark hold kubeadm

kubeadm version

